version: '3.8'

services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_DATABASE: questionPro
      DATABASE_HOST: localhost
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql

  app:
    build: .
    command: /bin/bash -c "/wait-for-it.sh database:3306 -- node dist/app.js"
    depends_on:
      - database
    ports:
      - "3000:3000"

